### ISSUE TITLE
PANIC in show log

### ISSUE THREAD

**Issue by parsley42** [lnxjedi/gopherbot#50]
```Aug 02 09:20:57 gir.skyline gopherbot[22951]: Error: PANIC from 'show log': runtime error: invalid memory address or nil pointer dereference
Aug 02 09:20:57 gir.skyline gopherbot[22951]: Stack trace:goroutine 162 [running]:
Aug 02 09:20:57 gir.skyline gopherbot[22951]: runtime/debug.Stack(0xc0005d1318, 0xac32a0, 0x1162400)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.checkPanic(0xc0005d1f68, 0xc0004085b1, 0x8)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/util.go:52 +0x6e
Aug 02 09:20:57 gir.skyline gopherbot[22951]: panic(0xac32a0, 0x1162400)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.(*Robot).SendUserMessage(0xc0005d1538, 0xc00034a75c, 0x4, 0xc0001ecd80, 0x5f, 0xc0001ecd80)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/robot_connector_methods.go:158 +0x4a
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.(*botContext).debugTask(0xc00036c2c0, 0xc0005c2160, 0xc0003f24c0, 0x38, 0xc0005d1500)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/debug.go:115 +0x45a
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.(*botContext).pluginAvailable.func1(0xc0005d16d0, 0xc00036c2c0, 0xc0005c2160, 0xc0003f2400,
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/available.go:26 +0x66
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.(*botContext).pluginAvailable(0xc00036c2c0, 0xc0005c2160, 0x0, 0x1)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/available.go:71 +0x54b
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.(*botContext).checkPluginMatchersAndRun(0xc00036c2c0, 0x1, 0x11744e0)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/dispatch.go:43 +0xcc4
Aug 02 09:20:57 gir.skyline gopherbot[22951]: github.com/lnxjedi/gopherbot/bot.(*botContext).handleMessage(0xc00036c2c0)
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/dispatch.go:227 +0x1168
Aug 02 09:20:57 gir.skyline gopherbot[22951]: created by github.com/lnxjedi/gopherbot/bot.handler.IncomingMessage
Aug 02 09:20:57 gir.skyline gopherbot[22951]: /var/lib/gopherbot/workspace/github.com/lnxjedi/gopherbot/master/bot/handler.go:188 +0x96c```

**Comment by parsley42** [comment]
Closing in favor of #175
